@startuml architecture-overview
  skinparam component {
    BackgroundColor<<App>> IndianRed
    BackgroundColor<<Lib>> Chocolate
  }
  skinparam interface {
    BackgroundColor GoldenRod
  }

  [ReactNativeApp] as rna <<App>>
  [node_js_app] as nja <<App>>

  [core] <<Lib>>
  () errors
  () components
  () file_toy

  core <== rna : inits
  core <== nja
  core <-up- errors

  rna <- file_toy
  file_toy -> nja
  rna <-- components

  file_toy <- core : is consumed by
@enduml